platform :ios, '15.5'

# react-native pods dosyasını doğrudan require ediyoruz.
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RNCodepushTest' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Uygulamanızın kök dizinine mutlak yol belirtir.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'CodePush', :path => '../node_modules/@chlee1001/react-native-code-push'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end